// AUTOGENERATED - DO NOT EDIT THIS FILE
// Components
import '../../ui/components/dropdown/dropdown.template.js';
import '../../ui/components/checkbox/checkbox.template.js';
import '../../ui/components/tags/tags.template.js';
import '../../ui/components/input_text/input_text.template.js';
import '../../ui/components/textarea/textarea.template.js';
// Layouts
import '../../ui/layouts/basicLayout/basicLayout.template.js';
// Views
import '../../ui/views/home/home.template.js';
import '../../ui/views/common/header/header.template.js';
import '../../ui/views/common/footer/footer.template.js';
