#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/"
FILE_NAME=`basename "$0"`
ABS_PATH="$DIR$FILE_NAME"

cd "$DIR../"

if [[ -z "${1// }" ]];
then
	truncate client/main.less -s 0
	echo '// AUTOGENERATED - DO NOT EDIT THIS FILE' > client/main.less

	find imports -name "*.less" | xargs -n1 "$ABS_PATH"

	echo "done"
else
	echo "@import '{}/$1';" >> client/main.less
fi
