#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/"
FILE_NAME=`basename "$0"`
ABS_PATH="$DIR$FILE_NAME"

cd "$DIR../imports"

if [[ -z "${1// }" ]];
then
	truncate startup/client/templates.js -s 0
	echo '// AUTOGENERATED - DO NOT EDIT THIS FILE' > startup/client/templates.js

	echo "// Components" >> startup/client/templates.js
	find ui/components -name "*.template.js" | xargs -n1 "$ABS_PATH"

	echo "// Layouts" >> startup/client/templates.js
	find ui/layouts -name "*.template.js" | xargs -n1 "$ABS_PATH"

	echo "// Views" >> startup/client/templates.js
	find ui/views -name "*.template.js" | xargs -n1 "$ABS_PATH"

	echo "done"
else
	echo "import '../../$1';" >> startup/client/templates.js
fi
